---
- name: Private keys
  openssl_privatekey:
      path: "{{ cert.value.privatekey_file }}"
      cipher: "{{ cert.value.cipher | default( omit ) }}"
      passphrase: "{{ cert.value.privatekey_passphrase | default( omit ) }}"
      size: "{{ cert.value.size | default( '4096' ) }}"
      state: "{{ cert.value.state | default( 'present' ) }}"
      type: "{{ cert.value.type | default( 'RSA' ) }}"
  loop: "{{ tls_certificates | dict2items }}"
  loop_control:
      loop_var: cert
- name: Public keys
  openssl_publickey:
      path: "{{ cert.value.publickey_file }}"
      privatekey_path: "{{ cert.value.privatekey_file }}"
      privatekey_passphrase: "{{ cert.value.passphrase | default( omit ) }}"
  loop: "{{ tls_certificates | dict2items }}"
  loop_control:
      loop_var: cert
- name: Certificate Signing Requests
  openssl_csr:
      path: "{{ cert.value.csr_file }}"
      privatekey_path: "{{ cert.value.privatekey_file }}"
      privatekey_passphrase:
          "{{ cert.value.privatekey_passphrase | default( omit ) }}"
      organization_name: "{{ cert.value.organization_name }}"
      organizational_unit_name:
          "{{ cert.value.organizational_unit_name | default( '' ) }}"
      country_name: "{{ cert.value.country_name }}"
      state_or_province_name: "{{ cert.value.state_or_province_name }}"
      locality_name: "{{ cert.value.locality_name }}"
      common_name: "{{ cert.value.common_name }}"
      email_address: "{{ cert.value.email_address | default( '' ) }}"
      subject_alt_name: "{{ cert.value.alt_names }}"
  loop: "{{ tls_certificates | dict2items }}"
  loop_control:
      loop_var: cert
